export function SHIP_PROPERTIES() {
  const shipArray = {
    miniDefenderOne: {
      cellSize: 2,
      offsetX: 0.15,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
    miniDefenderTwo: {
      cellSize: 2,
      offsetX: 0.15,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
    defenderOne: {
      cellSize: 3,
      offsetX: 0.1,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
    defenderTwo: {
      cellSize: 3,
      offsetX: 0.1,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
    destroyer: {
      cellSize: 4,
      offsetX: 0.1,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
    submarine: {
      cellSize: 4,
      offsetX: 0.1,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
    aircraftCarrier: {
      cellSize: 5,
      offsetX: 0.1,
      alignment: "horizontal",
      hovered: false,
      selected: false,
      cellLocation: [],
      bomedLocation: [],
      displayShip: false,
    },
  };
  return shipArray;
}
